// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonDatabase.DataAccess.Models;

namespace PokemonDatabase.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190301182936_AddTablesForPokemon")]
    partial class AddTablesForPokemon
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PokemonDatabase.DataAccess.Models.Ability", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("PokemonDatabase.DataAccess.Models.BaseHappiness", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("Happiness");

                    b.HasKey("ID");

                    b.ToTable("BaseHappiness");
                });

            modelBuilder.Entity("PokemonDatabase.DataAccess.Models.CaptureRate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("CatchRate");

                    b.Property<decimal>("ChanceOfCapture");

                    b.HasKey("ID");

                    b.ToTable("CaptureRates");
                });

            modelBuilder.Entity("PokemonDatabase.DataAccess.Models.Classification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Classifications");
                });

            modelBuilder.Entity("PokemonDatabase.DataAccess.Models.EggCycle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("CycleCount");

                    b.HasKey("ID");

                    b.ToTable("EggCycles");
                });

            modelBuilder.Entity("PokemonDatabase.DataAccess.Models.EggGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("EggGroups");
                });

            modelBuilder.Entity("PokemonDatabase.DataAccess.Models.ExperienceGrowth", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExpPointTotal");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("ExperienceGrowths");
                });

            modelBuilder.Entity("PokemonDatabase.DataAccess.Models.GenderRatio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("FemaleRatio");

                    b.Property<double>("MaleRatio");

                    b.HasKey("ID");

                    b.ToTable("GenderRatios");
                });

            modelBuilder.Entity("PokemonDatabase.DataAccess.Models.Generation", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<string>("Games");

                    b.Property<string>("Region");

                    b.HasKey("ID");

                    b.ToTable("Generations");
                });

            modelBuilder.Entity("PokemonDatabase.DataAccess.Models.Pokemon", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BaseHappinessID");

                    b.Property<int?>("CaptureRateID");

                    b.Property<int?>("ClassificationID");

                    b.Property<int?>("EggCycleID");

                    b.Property<int>("ExpYield");

                    b.Property<int?>("ExperienceGrowthID");

                    b.Property<int?>("GenderRatioID");

                    b.Property<string>("GenerationID");

                    b.Property<decimal>("Height");

                    b.Property<string>("Name");

                    b.Property<decimal>("Weight");

                    b.HasKey("ID");

                    b.HasIndex("BaseHappinessID");

                    b.HasIndex("CaptureRateID");

                    b.HasIndex("ClassificationID");

                    b.HasIndex("EggCycleID");

                    b.HasIndex("ExperienceGrowthID");

                    b.HasIndex("GenderRatioID");

                    b.HasIndex("GenerationID");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PokemonDatabase.DataAccess.Models.Type", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("PokemonDatabase.DataAccess.Models.Pokemon", b =>
                {
                    b.HasOne("PokemonDatabase.DataAccess.Models.BaseHappiness", "BaseHappiness")
                        .WithMany()
                        .HasForeignKey("BaseHappinessID");

                    b.HasOne("PokemonDatabase.DataAccess.Models.CaptureRate", "CaptureRate")
                        .WithMany()
                        .HasForeignKey("CaptureRateID");

                    b.HasOne("PokemonDatabase.DataAccess.Models.Classification", "Classification")
                        .WithMany()
                        .HasForeignKey("ClassificationID");

                    b.HasOne("PokemonDatabase.DataAccess.Models.EggCycle", "EggCycle")
                        .WithMany()
                        .HasForeignKey("EggCycleID");

                    b.HasOne("PokemonDatabase.DataAccess.Models.ExperienceGrowth", "ExperienceGrowth")
                        .WithMany()
                        .HasForeignKey("ExperienceGrowthID");

                    b.HasOne("PokemonDatabase.DataAccess.Models.GenderRatio", "GenderRatio")
                        .WithMany()
                        .HasForeignKey("GenderRatioID");

                    b.HasOne("PokemonDatabase.DataAccess.Models.Generation", "Generation")
                        .WithMany()
                        .HasForeignKey("GenerationID");
                });
#pragma warning restore 612, 618
        }
    }
}
